# Generated by Django 4.2.5 on 2023-09-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jobpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='expires_on',
            field=models.DateField(null=True),
        ),
    ]
